version: '3.8'

services:
 ragapi-app-dev:
    image: ragapiservices
    container_name: ragapi-dev
    build:
      context: .
      dockerfile: Deployment/Dockerfile
    ports:
      - "8000:8000"
    environment:
      ENV: dev
    volumes:
      - ./Sources/RAGAPIServices/certs:/app/RAGAPIServices/certs:ro
    networks:
      - fastapi_mongo_net
      
    restart: unless-stopped

networks:
  fastapi_mongo_net:
    external: true
